<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="9" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Test automtion suite" duration-ms="8152" started-at="2021-05-02T10:54:07Z" finished-at="2021-05-02T10:54:15Z">
    <groups>
    </groups>
    <test name="LoginPageTest" duration-ms="4769" started-at="2021-05-02T10:54:07Z" finished-at="2021-05-02T10:54:12Z">
      <class name="com.qa.saucedemo.test.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="setUp" is-config="true" duration-ms="3162" started-at="2021-05-02T10:54:07Z" finished-at="2021-05-02T10:54:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLoginPageTitleTest()[pri:0, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="verifyLoginPageTitleTest" is-config="true" duration-ms="10" started-at="2021-05-02T10:54:10Z" depends-on-methods="com.qa.saucedemo.base.BaseTest.setUp" finished-at="2021-05-02T10:54:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="loginTest" is-config="true" duration-ms="292" started-at="2021-05-02T10:54:10Z" finished-at="2021-05-02T10:54:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="testCase2_Part1()[pri:3, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="testCase2_Part1" duration-ms="367" started-at="2021-05-02T10:54:11Z" finished-at="2021-05-02T10:54:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2_Part1 -->
        <test-method status="PASS" signature="addToCartTest()[pri:4, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="addToCartTest" duration-ms="178" started-at="2021-05-02T10:54:11Z" finished-at="2021-05-02T10:54:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToCartTest -->
        <test-method status="PASS" signature="testCase2_Part3()[pri:5, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="testCase2_Part3" duration-ms="77" started-at="2021-05-02T10:54:11Z" finished-at="2021-05-02T10:54:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase2_Part3 -->
        <test-method status="PASS" signature="doCheckoutTest()[pri:6, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="doCheckoutTest" duration-ms="293" started-at="2021-05-02T10:54:11Z" finished-at="2021-05-02T10:54:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doCheckoutTest -->
        <test-method status="PASS" signature="paymentInfoTest()[pri:7, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="paymentInfoTest" duration-ms="24" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentInfoTest -->
        <test-method status="PASS" signature="shippingInfoTest()[pri:8, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="shippingInfoTest" duration-ms="24" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shippingInfoTest -->
        <test-method status="PASS" signature="totalAmountTest()[pri:9, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="totalAmountTest" duration-ms="23" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- totalAmountTest -->
        <test-method status="PASS" signature="finishTest()[pri:10, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="finishTest" duration-ms="85" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finishTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.saucedemo.test.LoginPageTest@3a93b025]" name="tearDown" is-config="true" duration-ms="104" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.saucedemo.test.LoginPageTest -->
    </test> <!-- LoginPageTest -->
    <test name="TC1LoginPageError" duration-ms="3082" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:15Z">
      <class name="com.qa.saucedemo.test.TC1LoginPageError">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.saucedemo.test.TC1LoginPageError@1bd4fdd]" name="setUp" is-config="true" duration-ms="2268" started-at="2021-05-02T10:54:12Z" finished-at="2021-05-02T10:54:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLoginPageTitleTest()[pri:0, instance:com.qa.saucedemo.test.TC1LoginPageError@1bd4fdd]" name="verifyLoginPageTitleTest" is-config="true" duration-ms="7" started-at="2021-05-02T10:54:14Z" finished-at="2021-05-02T10:54:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="FAIL" signature="invalidLoginTest()[pri:0, instance:com.qa.saucedemo.test.TC1LoginPageError@1bd4fdd]" name="invalidLoginTest" duration-ms="330" started-at="2021-05-02T10:54:14Z" finished-at="2021-05-02T10:54:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.saucedemo.test.TC1LoginPageError.invalidLoginTest(TC1LoginPageError.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.saucedemo.test.TC1LoginPageError@1bd4fdd]" name="tearDown" is-config="true" duration-ms="92" started-at="2021-05-02T10:54:15Z" finished-at="2021-05-02T10:54:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.saucedemo.test.TC1LoginPageError -->
    </test> <!-- TC1LoginPageError -->
  </suite> <!-- Test automtion suite -->
</testng-results>
